sudo: false
language: node_js
node_js:
- '4.1'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
after_success:
- npm run deploy
env:
  global:
  - secure: ivSxxOovTR6anBNo0onK9C9EUJkaiwZCxSfPOOFfjSW6oe+/ZPOj6mG+hQlLGwScMzA//gDNKSQkI4p0jdsIdrZidOHrG4Vj2i/10h8nSGtsaur8MrNEPV8jTDsWdRlU43KqEVPCqiQ54jzH/tnf3Isy8dH8IHXla9RkXbey6SbcVFPc+oF7qBNdKXM5ei54UYo6iiVtJlGxB271pj1X0S8u7AAryDuTigNQmWbrttrr1jeIvMvsCHrf2tDVDp71J71aG13nEgDbcSfpC5h5gfr2aEfJvvao4DnyCcaDZDfxwwMTGn5v0ntBHJnbdt/XTVhbGE4Bq421imC6UV2SvIJ1Eupd34Lise1E2E4JJ8zArfBiHpDB7D7VUxuGDRmd+PYQq3XIE8OoV95eTuwANFick/jG8Z+MFZND5ffCiZj54f6RC4KPpRMYMuKQWt+9MWSq5xvq1Hpibm6ooSbqKilMQRYGR4I8k2DOwuirFNkkeyRcddJlbjAc1mtqauCYPCpoatI+QnNgQlOgPNpJcfeiGXvDL3/s391Aur9JHVw7V5LSssqGA2yucFAkAK3F0C35W91NVfLMhCM5eX72mHJW2rMSvh60cQyrC8fSihc8JsxfZ+ddxK/vtA8dXZ9ltrXTMD4jiykf/g3k63kN9UdLZVyELuGA9xyvISEqFEY=
